#ifndef CONSTANTS_H
#define CONSTANTS_H

#define X_SIZE 10
#define Y_SIZE 18
#define WINDOW_W 1
#define WINDOW_H 1
#define PIECE_DELAY 400
#define SCREEN_FACTOR 4
#define PIXEL_ORIGINAL_SIZE 8
#define SCREEN_POS_X 11
#define SCREEN_POS_Y 0
#define SCORE_NUMBER_POS_X 109
#define SCORE_NUMBER_POS_Y 27
#define LEVEL_NUMBER_POS_X 127
#define LEVEL_NUMBER_POS_Y 50
#define LINES_NUMBER_POS_X 109
#define LINES_NUMBER_POS_Y 72
#define SCORE_DIGITS 5
#define LEVEL_DIGITS 2
#define LINES_DIGITS 5

#endif
